### PR TITLE
feat(server): add update API request

### LINKED ISSUE #45: f2: Edit caption on backend
Create an api request to edit the selected caption

### PR DESCRIPTION
**Pull request by ChelleAmon**
## Changes
1. Create an api call to update captions on backend

## Purpose
Set up a Put API request on server

## Approach
Setting up Update operation on backend

## Learning
https://www.tabnine.com/code/javascript/functions/mongoose/Model/findByIdAndUpdate
Also referred from my previous project

Closes #45

### CODE REVIEW

**Comment by ChelleAmon** [comment]
It will also be ready once the other PRs are merged

**Comment by jacquelinemartinez6114** [comment]
I am not fluent in this language, but the link helps

**Review by brycejjacks — APPROVED** [review]
this looks like a model update .. way to use put.. and you refreshed me about $set

**Review by Big3D — APPROVED** [review]
Piggybacking off of Bryce's review

**Pull request merged**
