### PR TITLE
Gsa 29 setup mongodb atlas

### LINKED ISSUE #29: (f2)Feat: create to cloud database
-Create a connection with mongoDB atlas, a cloud database where everyone will have access to same database

### PR DESCRIPTION
**Pull request by ChelleAmon**
## Changes
1. Create a cloud database with mongoDB Atlas
2. install dotenv npm dependency by running `npm i dotenv --save` in the terminal
3. refactor mongoDB connection on server.js

## Purpose
Having our project connected to a cloud database will allow developers to have access to one database but still has the option to work on their local database if they wish to test on their own

## Approach
We will all have access to one database without the need for anyone to  install mongoDB locally on their computer

## Learning
https://www.mongodb.com/atlas/database
https://www.freecodecamp.org/news/how-to-use-node-environment-variables-with-a-dotenv-file-for-node-js-and-npm/

Closes #29

### CODE REVIEW

**Comment by ChelleAmon** [comment]
Hello! When you request to get data from the API, you should see 5 captions in your postman

**Comment by jacquelinemartinez6114** [comment]
Good Job! Tested with postman and worked. My first time working with Postman!

**Review by jacquelinemartinez6114 — APPROVED** [review]
Good Job! Tested with postman and worked. My first time working with Postman!

**Review by Aman-codde — APPROVED** [review]
tested the api, it's working! good job Gichelle!

**Pull request merged**
